### ISSUE TITLE
Git ignore for you

### ISSUE THREAD

**Issue by BhJaipal** [nitinya9av/cpp#1]
First: do a change code in code runner execution map
Go to settings > You will see a icon to open a settings.json
Write `"code-runner.executorMap"`, VSCode intellisence will give you a suggestion like that, press enter for "c" and c++, change those to 
```json
{
  "code-runner.executorMap": {
    ...
    "c": "gcc $fileName -o $fileNameWithoutExt.exe && ./$fileNameWithoutExt.exe",
    "cpp": "g++ $fileName -o $fileNameWithoutExt.exe && ./$fileNameWithoutExt.exe"
    ...
  }
}
```

Then add a .gitignore file and add below
```ignore
*.exe
```

**Comment by nitinya9av** [comment]
Will include.
